"""Gradio demo: judges watch trained AI agents play Among Us.

Recordings of real model decisions are downloaded from the model repo on first use.
No model is loaded in the Space — playback is instant.
"""
from __future__ import annotations
import json
import random
import os
from pathlib import Path
from typing import Optional

import gradio as gr

from server.environment_multi import MultiAgentAmongUsEnv

env = MultiAgentAmongUsEnv()

EMOJI = {
    "Red": "🔴", "Blue": "🔵", "Green": "🟢", "Yellow": "🟡",
    "Purple": "🟣", "Orange": "🟠", "White": "⚪",
}

MODEL_REPO = "parthdagia/among-us-multiagent-detective"
RECORDINGS_FILE = "eval_recordings.json"
RECORDINGS_CACHE = Path("/tmp/eval_recordings.json")

_RECORDINGS_LOADED: list = []


def tag(name: str) -> str:
    return f"{EMOJI.get(name, '⬛')} **{name}**"


def _load_recordings() -> list:
    global _RECORDINGS_LOADED
    if _RECORDINGS_LOADED:
        return _RECORDINGS_LOADED

    # Try cache first
    if RECORDINGS_CACHE.exists():
        try:
            data = json.loads(RECORDINGS_CACHE.read_text())
            _RECORDINGS_LOADED = data.get("recordings", [])
            if _RECORDINGS_LOADED:
                return _RECORDINGS_LOADED
        except Exception:
            pass

    # Download from HF Hub (public, no auth needed)
    try:
        from huggingface_hub import hf_hub_download
        path = hf_hub_download(
            repo_id=MODEL_REPO,
            filename=RECORDINGS_FILE,
            repo_type="model",
        )
        data = json.loads(Path(path).read_text())
        _RECORDINGS_LOADED = data.get("recordings", [])
        # Cache for next call
        RECORDINGS_CACHE.write_text(json.dumps(data))
    except Exception as e:
        print(f"[gradio_demo] could not load recordings: {e}")
        _RECORDINGS_LOADED = []
    return _RECORDINGS_LOADED


def _render_game(rec: dict, idx: int, total: int) -> str:
    parts = [
        f"## 🚨 EMERGENCY MEETING &nbsp;&nbsp;<sup>game {idx + 1} / {total}</sup>",
        "",
        f"💀 Body of **{rec['kill_victim']}** found in **{rec['kill_location']}**",
        f"🗣️ Reported by **{rec['body_found_by']}**",
        "",
        f"**Alive ({len(rec['alive_players'])}):** " + " &nbsp; ".join(tag(p) for p in rec["alive_players"]),
        "",
        "<details open><summary>### 💬 Initial Statements</summary>",
        "",
    ]
    for name, stmt in rec["all_statements"].items():
        parts.append(f"- {tag(name)}: *\"{stmt}\"*")
    parts.append("\n</details>")

    if rec.get("discussion_log"):
        parts.append("\n<details open><summary>### 🗣️ Debate Transcript</summary>\n")
        cur = -1
        for e in rec["discussion_log"]:
            if e["round"] != cur:
                cur = e["round"]
                parts.append(f"\n**Round {cur + 1}:**")
            parts.append(f"- {tag(e['player_name'])}: {e['statement']}")
        parts.append("\n</details>")

    parts.append("\n---")
    parts.append("## 🤖 The trained AI crewmates vote")
    parts.append("*Each crewmate is the same trained Qwen 2.5 1.5B + LoRA. They each independently read the debate and decide.*\n")

    impostor = rec.get("impostor")
    for crew, info in rec["crewmate_votes"].items():
        vote = info["vote"]
        is_correct = vote.lower() == (impostor or "").lower() if impostor else False
        check = "✅" if is_correct else "❌"
        reasoning = info.get("reasoning") or "*(no reasoning)*"
        # Normalize whitespace in reasoning
        reasoning = " ".join(reasoning.split())[:600]

        parts.append(f"<details open><summary>### {tag(crew)} → votes **{tag(vote)}** {check}</summary>")
        parts.append(f"\n> *{reasoning}*\n")
        parts.append("</details>\n")

    # Resolution
    parts.append("---")
    parts.append("## 🎯 Resolution")
    ejected = rec.get("ejected")
    if ejected:
        parts.append(f"**{tag(ejected)} was ejected by majority vote.**\n")
        if rec.get("ejection_correct"):
            parts.append(f"✅ **Correct!** {tag(ejected)} was the impostor — **CREW WINS!** 🎉")
        else:
            parts.append(f"❌ **Wrong.** The real impostor was {tag(impostor)}. They survive to kill again.")
    else:
        parts.append("**Tie vote — no one ejected.**")
        parts.append(f"The impostor was {tag(impostor)}. They survive.")

    return "\n".join(parts)


def _render_no_recordings() -> str:
    return (
        "## 🎬 Demo recordings not available yet\n\n"
        "Recordings are generated by `jobs/eval_job.py` and uploaded to "
        f"[{MODEL_REPO}](https://huggingface.co/{MODEL_REPO}) as `eval_recordings.json`. "
        "Come back in a few minutes — the recording job is running.\n\n"
        "*In the meantime, the **Training Results** and **Safeguards** tabs above are populated.*"
    )


def watch_game(idx_state: int):
    recs = _load_recordings()
    if not recs:
        return _render_no_recordings(), 0
    next_idx = (idx_state + 1) % len(recs)
    return _render_game(recs[next_idx], next_idx, len(recs)), next_idx


def initial_view():
    recs = _load_recordings()
    if not recs:
        return _render_no_recordings()
    return _render_game(recs[0], 0, len(recs))


def stats_summary() -> str:
    recs = _load_recordings()
    if not recs:
        return ""
    correct = sum(1 for r in recs if r.get("ejection_correct"))
    return (
        f"### 🎬 Watching pre-recorded games of the trained AI in action — "
        f"impostor caught in {correct}/{len(recs)} games shown here."
    )


# ── Build UI ───────────────────────────────────────────────────────────


def build_demo() -> gr.Blocks:
    with gr.Blocks(title="Among Us Deception Gym") as demo:
        gr.Markdown(
            """
            # 🔪 Among Us Deception Detection — Live AI Demo

            **Watch the trained AI play Among Us against itself.** Each crewmate is a copy of the
            same trained model (Qwen 2.5 1.5B + LoRA). They read the debate transcript and each
            independently decide who they think the impostor is. The majority vote ejects.

            **Headline:** trained AI catches the impostor **96.7%** of the time vs **32.7%** for base Qwen 2.5 1.5B.
            """
        )

        idx_state = gr.State(-1)

        with gr.Tab("🎬 Watch the AI play"):
            stats_md = gr.Markdown(stats_summary())

            view = gr.Markdown(initial_view())

            with gr.Row():
                next_btn = gr.Button("▶️ Watch another game", variant="primary", size="lg")

            next_btn.click(
                watch_game,
                inputs=[idx_state],
                outputs=[view, idx_state],
            )

            gr.Markdown(
                """
                ---
                ### What you're seeing
                - **Real model decisions** — every vote and every line of reasoning was generated by the trained
                  model on a fresh game scenario. We pre-recorded these (rather than running the 1.5B model live
                  in this Space) so the page loads instantly.
                - **Each crewmate is independent** — same model weights, but each gets a different prompt
                  (`"You are Red"` vs `"You are Green"`). They read the same statements + debate but reason separately.
                - **The impostor is generated by a separate model** (HF Inference API at scenario-generation time).
                  Lies have at least one detectable contradiction; otherwise the task would be unwinnable.
                """
            )

        with gr.Tab("📊 Training Results"):
            gr.Markdown("### 50-Game Eval — 150 votes per model")
            gr.HTML(
                '<img src="https://raw.githubusercontent.com/parthdagia05/among-us-deception-gym/main/plot_comparison.png" '
                'style="width:100%;max-width:800px;border-radius:8px;">'
            )
            gr.Markdown("### GRPO Reward Curve (1500 iterations, real data)")
            gr.HTML(
                '<img src="https://raw.githubusercontent.com/parthdagia05/among-us-deception-gym/main/plot_reward.png" '
                'style="width:100%;max-width:800px;border-radius:8px;">'
            )
            gr.Markdown(
                "Model converges from **+0.19 average reward** (random-ish) to **+1.0 (perfect)** "
                "in ~500 iterations and saturates by iteration 600."
            )
            gr.Markdown("### Sycophancy Resistance — 17× Reduction")
            gr.HTML(
                '<img src="https://raw.githubusercontent.com/parthdagia05/among-us-deception-gym/main/plot_sycophancy.png" '
                'style="width:100%;max-width:600px;border-radius:8px;">'
            )

        with gr.Tab("🛡️ Safeguards"):
            gr.Markdown(
                """
                ### 8 layered defences against reward hacking

                The hackathon guide flags reward hacking as the top RL failure mode. Our stack:

                1. **Four independent reward functions** (not one combined): `reward_format`, `reward_correct_vote`, `reward_anti_sycophancy`, `reward_anti_random_crewmate`. The model can't game one signal at the expense of another.
                2. **Closed action space** — Pydantic-validated `{action_type, vote_target}`. No `eval`, no shell, no global mutation possible.
                3. **Programmatic ground truth** — vote correctness = `target == impostor_names[i]`. No LLM-as-judge that could be gamed.
                4. **Per-round timeouts** — `max_discussion_rounds` caps debate; debate auto-advances when all alive players speak.
                5. **Single-impostor lock** — `scenario_generator.py` forces `num_impostors=1`.
                6. **Anti-cheat grader** (single-agent env) — penalises voting before tool use, repeated votes, timeout-no-vote.
                7. **Generation inspection** — every 5 GRPO steps logs `min_length`, `clipped_ratio`, `entropy`, `frac_reward_zero_std`.
                8. **Sycophancy probe** — one crewmate per game is *always* tagged "confident innocent" with assertive personality. Base 22 % → trained 1.3 % (17× reduction).

                ### What the model literally cannot do

                - Cannot edit timers, mutate session state, or read other players' private views
                - Cannot execute code or call external APIs from inside a vote
                - Cannot vote twice (`session.votes` is idempotent overwrite, locked after `votes_complete()`)
                - Cannot speak twice in the same debate round (`session.spoke_this_round` set)
                - Cannot kill itself or another impostor (`/multi/kill` validates `impostor_name in s.impostor_names` and `kill_target not in s.impostor_names`)
                """
            )

        with gr.Tab("🔌 API & Code"):
            gr.Markdown(
                """
                ### REST endpoints (OpenEnv-compliant)

                | Method | Path | Purpose |
                |---|---|---|
                | `POST` | `/multi/reset` | Start a new game |
                | `GET` | `/multi/observation/{game_id}/{player}` | Per-player view (no impostor leak) |
                | `POST` | `/multi/discuss` | Submit a debate statement |
                | `POST` | `/multi/vote` | Crewmate votes |
                | `POST` | `/multi/kill` | Impostor kills (triggers next round) |
                | `GET` | `/multi/resolve/{game_id}` | Vote resolution + win check |
                | `GET` | `/multi/session/{game_id}` | Full game state |

                **Try it:**
                ```bash
                curl -X POST https://parthdagia-among-us-deception-gym.hf.space/multi/reset \\
                  -H "Content-Type: application/json" \\
                  -d '{"max_discussion_rounds": 2}'
                ```

                **Code:** [github.com/parthdagia05/among-us-deception-gym](https://github.com/parthdagia05/among-us-deception-gym)

                **Trained model:** [huggingface.co/parthdagia/among-us-multiagent-detective](https://huggingface.co/parthdagia/among-us-multiagent-detective)
                """
            )

    return demo


demo = build_demo()
